"""empty message

Revision ID: 506d5697ff2c
Revises: 7270111f509c
Create Date: 2022-05-23 16:34:48.523119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '506d5697ff2c'
down_revision = '7270111f509c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_describtion', sa.Text(), nullable=True))
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('Show', 'date_time')
    op.drop_column('Show', 'name')
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_describtion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_describtion')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'genres')
    op.add_column('Show', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'start_time')
    op.drop_column('Artist', 'seeking_describtion')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
